packages/theme/src/themes/atb-theme/theme.css
packages/theme/src/themes/atb-theme/theme.module.css
packages/theme/src/themes/atb-theme/theme.ts

Oppdaget at feil grønnfarge ble brukt for valid status etter #12, som nå er oppdatert til å matche Figma

fix: update AtB status valid color

---

packages/theme/src/typography.css
packages/theme/src/typography.module.css
packages/theme/src/typography/android.ts
packages/theme/src/typography/ios.ts
packages/theme/src/typography/types.ts
packages/theme/tools/create-typo.ts
web/src/guide/index.tsx

Legger til ny tekst type "label__uppercase", som finnes i [Figma](https://www.figma.com/file/3rlcixpbhfBglNSctUkMys/Theme-1.0?node-id=26%3A2). Denne krevde også at `textTransform` skal kunne settes til `uppercase`, så legger til det som del av TextStyle-typen.
Hadde en diskusjon med @hildeor om tekststørrelse og linehøyde er riktig, her tar vi muligens en ny runde og oppdaterer når vi får testet det i praksis.

feat: add label__uppercase text style

---

packages/assets/package.json
packages/theme/package.json
packages/theme/src/theme.ts
packages/theme/src/themes/atb-theme/theme.css
packages/theme/src/themes/atb-theme/theme.module.css
packages/theme/src/themes/atb-theme/theme.ts
packages/theme/src/themes/nfk-theme/theme.css
packages/theme/src/themes/nfk-theme/theme.module.css
packages/theme/src/themes/nfk-theme/theme.ts

Adds missing static background accent 5 which is specified in the design system and used on the webshop (footer).
cc @toretefre Should add for NFK after we find what colors it should be.

fix: adds missing accent 5 color

---

packages/theme/src/themes/nfk-theme/theme.ts

Only used as ActiveTint-color in App TabNavigator (as seen in Reisesøk at bottom of picture)

fix: update NFK LM_interactive_2_outline

---

packages/assets/package.json
packages/assets/src/bin.ts
packages/assets/src/generateTs.ts
packages/assets/src/utils.ts

When working on Storybook it became even more apparent for the webshop that doing manual file paths isn't the most ergonomic way to interact with icons. We have some needs:
1. Don't want to create bundle with icons that includes several icons we don't use
2. We do want to have static resolving of icons to help us see what icons we have.
3. We do want to have constructs that can automatically set dark/light mode.
This PR generates (fully backwards compatible) types based on all icons that are parsed, either its only mono, colors or all.
**This is currently an experiment to see how we can improve icons in the webshop.**
---
Docs:
```
Usage: npx @atb-as/generate-assets [options] <type> <orgId>
Arguments:
type                           Type of assets to generate (choices: "colors", "all", …
```

feat: adds generated icon types

---

packages/assets/package.json

Downgrading dependency, to one thats actually available on npm, after failing to publish alpha.8.

fix: use alpha.7 as theme dependency instead of non-available alpha.8

---

packages/assets/files/nfk/colors/illustrations/token/travelcard/dark/Travelcard.svg
packages/assets/files/nfk/colors/illustrations/token/travelcard/light/Travelcard.svg
packages/assets/files/nfk/colors/images/OnBehalfOf.svg

Related to https://github.com/AtB-AS/kundevendt/issues/2628
Includes for NFK:
- Size adjustment for on behalf of image, so it does not cover entire webshop2 page
- Removal of empty NFK specific travelcard illustration, so that the common illustration is used
Includes for AtB:
- Absolutely nothing

refactor: minor NFK token adjustments

---

packages/assets/src/tools/validate-files.ts

In the event of an org providing an org-specific asset file for something other organization uses a common file for, the validation of asset files now fails. An example of this is the travelcard asset, where AtB has provided their own t:kort illustration asset.
This pull requests makes the validation script check if a replacement file exists in the common folder, and only returns the exit code 1 if there is no common file.

fix: allow common assets files to be used if org file is not provided

---

packages/assets/files/fram/colors/images/dark/BackgroundIllustration-OnBehalfOf.svg
packages/assets/files/fram/colors/images/dark/BackgroundIllustration.svg
packages/assets/files/fram/colors/images/light/BackgroundIllustration-OnBehalfOf.svg
packages/assets/files/fram/colors/images/light/BackgroundIllustration.svg

I've removed the background illustrations for FRAM as they did not work well with the system because of the vertical separation of colors in the illustration

Remove background illustrations for FRAM

---

packages/theme/src/theme.ts
packages/theme/src/themes/atb-theme/theme.css
packages/theme/src/themes/atb-theme/theme.module.css
packages/theme/src/themes/atb-theme/theme.ts
packages/theme/src/themes/fram-theme/theme.css
packages/theme/src/themes/fram-theme/theme.module.css
packages/theme/src/themes/fram-theme/theme.ts
packages/theme/src/themes/nfk-theme/theme.css
packages/theme/src/themes/nfk-theme/theme.module.css
packages/theme/src/themes/nfk-theme/theme.ts

Add separate colors for the zone seliction overlay colors. The status and valid colors do not work NFK, so there's a need for additional colors.
Adds colors needed for https://github.com/AtB-AS/kundevendt/issues/3060

feat: Add color for zone selection

---

packages/theme/src/themes/fram-theme/theme.ts

Use darker color for background 1 as shown in the color palette. Changed the border-primary to a lighter tone to make the divider line in the footer visible. The inputs' border still looks okay.
Fixes https://github.com/AtB-AS/kundevendt/issues/3586

fix(FRAM): Update background_1 and border-primary in dark mode

---

packages/theme/src/themes/fram-theme/theme.css
packages/theme/src/themes/fram-theme/theme.module.css
packages/theme/src/themes/fram-theme/theme.ts

FRAM has a new blue primary color that is compliant with [WCAG 2.1 1.4.3](https://www.uutilsynet.no/wcag-standarden/143-kontrast-minimum-niva-aa/95) when used with a white text color.

feat: new blue color for FRAM

---

packages/theme/src/themes/fram-theme/theme.css
packages/theme/src/themes/fram-theme/theme.module.css
packages/theme/src/themes/fram-theme/theme.ts

Fixes https://github.com/AtB-AS/kundevendt/issues/4098 by using a darker color for interactive_2-active so that the text is white.

fix: mixed text color for FRAM in app

---

packages/assets/files/fram/colors/images/dark/TravelPlanning.svg
packages/assets/files/fram/colors/images/light/TravelPlanning.svg

Set height and width to fix scaling issues that hid the button on the flexibility info screen.
Fixes https://github.com/AtB-AS/kundevendt/issues/4216 after the assets are regenerated in the app.

fix: Add height and width to TravelPlanning

---

packages/theme/src/typography.css
packages/theme/src/typography.module.css
packages/theme/src/typography/android.ts
packages/theme/src/typography/ios.ts
packages/theme/src/typography/types.ts

[`body__primary--strike`](https://www.figma.com/file/3rlcixpbhfBglNSctUkMys/Text%2C-colors%2C-sizes-and-effects?type=design&node-id=2250-4671&mode=design&t=tExTA63d432gEGF4-4)  was needed for https://github.com/AtB-AS/kundevendt/issues/15925, and [`body__tertiary--uppercase`](https://www.figma.com/file/3rlcixpbhfBglNSctUkMys/Text%2C-colors%2C-sizes-and-effects?type=design&node-id=2256-4823&mode=design&t=tExTA63d432gEGF4-4) was also missing.

feat: add body__primary--strike and body__tertiary--uppercase text styles

---

packages/theme/src/sizes.ts
packages/theme/src/themes/atb-theme/theme.css
packages/theme/src/themes/atb-theme/theme.module.css
packages/theme/src/themes/fram-theme/theme.css
packages/theme/src/themes/fram-theme/theme.module.css
packages/theme/src/themes/nfk-theme/theme.css
packages/theme/src/themes/nfk-theme/theme.module.css

**Breaking change**: 
- Changes small icon size to 16
- Adds a new icon size, xSmall = 12
closes https://github.com/AtB-AS/kundevendt/issues/3834
1. Replace all occurrences of "small" icons with "xSmall" 
- https://github.com/AtB-AS/mittatb-app/pull/4274
3. Track down icons that are out of sync with Figma, and update them
There's a couple of occurrences of "small" icons, that probably can be replaced with "xSmall"
- https://github.com/AtB-AS/planner-web/pull/215
I found no occurrences of small icons 🤯 So no change should be needed.

feat!: add xSmall icon size and make small larger

---

packages/assets/package.json
packages/assets/src/generateTs.ts

File IDs generated in typescript types will not work as expected on Windows as paths aren't normalized when used as ID. This will cause generated-assets to generate wrong TypeScript definitions and icons will not match full paths.
This normalizes ot Unix pathing for IDs, making it consistent with existing use.

fix: issue with generating types on windows

---

packages/theme/package.json

CSS files were not copied to the `/lib` folder when running the build script. In accordance with the [copyfiles docs](https://www.npmjs.com/package/copyfiles), this solves the issue on Windows and should still work on Mac, **but this should be tested by a Mac used before merging**
**How to test**
1. Check out this branch on a Mac
3. run `cd packages/theme`
4. Make sure the `./lib` folder does not exist
5. run `yarn build`
6. The `./lib` folder should exist and should contain `typography.css` and `typography.module.css` in the root.

fix: glob for copying CSS files works on Windows

---

packages/theme/src/theme.ts
packages/theme/src/themes/atb-theme/theme.css
packages/theme/src/themes/atb-theme/theme.module.css
packages/theme/src/themes/atb-theme/theme.ts
packages/theme/src/themes/fram-theme/theme.css
packages/theme/src/themes/fram-theme/theme.module.css
packages/theme/src/themes/fram-theme/theme.ts
packages/theme/src/themes/innlandet-theme/theme.css
packages/theme/src/themes/innlandet-theme/theme.module.css
packages/theme/src/themes/innlandet-theme/theme.ts
packages/theme/src/themes/nfk-theme/theme.css
packages/theme/src/themes/nfk-theme/theme.module.css
packages/theme/src/themes/nfk-theme/theme.ts
packages/theme/src/themes/troms-theme/theme.css
packages/theme/src/themes/troms-theme/theme.module.css
packages/theme/src/themes/troms-theme/theme.ts

related to
- https://github.com/AtB-AS/kundevendt/issues/15379
- https://github.com/AtB-AS/kundevendt/issues/18138
- https://github.com/AtB-AS/kundevendt/issues/18136
also partly related to https://github.com/AtB-AS/kundevendt/issues/18132 (new label color)
This PR will update the color for `Status Colors`, as explained on the issues I linked above, there is a new color system for `MessageInfoBox`, and this results in the change below:
```
export type ContrastColor = {
background: string;
text: string;
};
status: {
valid: ContrastColor;
info: ContrastColor;
warning: ContrastColor;
error: ContrastColor;
};
```
```
export type ContrastColor = {
background: string;
text: string;
};
export type StatusColor = {
primary: ContrastColor;
secondary: ContrastColor;
};
status: {
valid: StatusColor; …
```

feat: update status color

---

packages/theme/src/themes/atb-theme/theme.ts

Reverts some of the color change for AtB in PR https://github.com/AtB-AS/design-system/pull/171
This will use the old color for both `primary` and `secondary`, so that at least we can update the usage in the app without any visual change.
A learning from this color system update, is that when we introduce new system, change the system with existing values first, and then update the values later. 📖 
PR on app : https://github.com/AtB-AS/mittatb-app/pull/4548

feat: revert atb color change

---

packages/theme/src/theme.ts
packages/theme/src/themes/atb-theme/theme.ts
packages/theme/src/themes/fram-theme/theme.ts
packages/theme/src/themes/innlandet-theme/theme.ts
packages/theme/src/themes/nfk-theme/theme.ts
packages/theme/src/themes/troms-theme/theme.ts

In order to show color-encoded geofencingZones in the map, `geofencingZones` is added to the design system.
<table>
<tr>
<td><img width="200" src="https://github.com/AtB-AS/design-system/assets/134292729/81365aa5-5961-440c-ad91-7014ee29067f" /></td>
<td><img width="200" src="https://github.com/AtB-AS/design-system/assets/134292729/fda7f76a-2325-4e0d-8932-2b2d6745ae74" /></td>
<td><img width="200" src="https://github.com/AtB-AS/design-system/assets/134292729/9e3592d2-9fa9-468e-b936-6db96552745c" /></td>
<td><img width="200" src="https://github.com/AtB-AS/design-system/assets/134292729/6692a93f-ffa1-4260-ba22-5ab2239c8413" /></td>
</tr>
<tr>
<td>Allowed</td>
<td>Slow</td>
<td>No Parking</td>
<td>No Entry</td>
</tr>
</table>
Resolves https://github.com/AtB-AS/kundevendt/issues/17614

feat: Add geofencingZones

---

packages/theme/src/themes/atb-theme/theme.css
packages/theme/src/themes/atb-theme/theme.module.css
packages/theme/src/themes/fram-theme/theme.css
packages/theme/src/themes/fram-theme/theme.module.css
packages/theme/src/themes/innlandet-theme/theme.css
packages/theme/src/themes/innlandet-theme/theme.module.css
packages/theme/src/themes/nfk-theme/theme.css
packages/theme/src/themes/nfk-theme/theme.module.css
packages/theme/src/themes/troms-theme/theme.css
packages/theme/src/themes/troms-theme/theme.module.css
packages/theme/tools/create-theme.ts

After the status colors were split out into their own set of colors (and not under static), their colors were not generated in the CSS. 
This is more than likely a breaking change in some of the applications, should preferrably have been in the same version as the changes in TypeScript, please comment on how we best should solve this.
Closes https://github.com/AtB-AS/kundevendt/issues/18515

fix: generate css status colors

---

packages/theme/src/themes/fram-theme/theme.css
packages/theme/src/themes/fram-theme/theme.module.css
packages/theme/src/themes/fram-theme/theme.ts

FRAM wanted their navbar and footer to be the same color some time ago. The recent color changes changed this. This causes issues because FRAM uses the FRAM logo in the navbar and footer, meaning one logo color should be possible to use in both places. I propose that we change the footer color to match the navbar color in light mode, as was done earlier so that the webshop feels more aligned with their homepage frammr.no and also fixes the problem with the logo. The color is only used by the webshop so this won't cause any other issues. 
Current colors:
With this change:

fix: fram webshop footer color

---

packages/theme/package.json
packages/theme/src/theme.ts
packages/theme/src/themes-fs/atb-theme/dark.ts
packages/theme/src/themes-fs/atb-theme/light.ts
packages/theme/src/themes-fs/atb-theme/theme.ts
packages/theme/src/themes-fs/index.ts
packages/theme/src/themes/atb-theme/dark.ts
packages/theme/src/themes/atb-theme/light.ts
packages/theme/src/themes/atb-theme/theme.css
packages/theme/src/themes/atb-theme/theme.module.css
packages/theme/tools/create-css.ts
packages/theme/tools/fetch-figma-variables.ts
packages/theme/tools/utils.ts

Since we do not wish to make a lot of changes to our (web) apps initially, I added a compatibility mode that transforms the new variable structure to the old variable structure, whilst maintaining the direct updates we get from Figma. 
_From the structure compared to version 10.x of `@atb-as/theme`_
**Removed**
- Removed `textColors` object in favor of `text` key in `Theme`;
- Removed ` baseColors` object. These are not to be used directly, but accessible through `Theme`;
- Removed `colors` object;
- Removed `backgrounds` object;
- - Removed transport color `‎transport_airport` and `‎transport_plane`.
**Changed**
- `geofencingZones` children are now lowercase instead of capitalized: `allowed`, `slow`, `noParking` and `noEntry`.
**Added**
- `ThemeOptions` added to `createThemeFor(variant, …

feat: Added compatibility mode to convert new Figma structure to old (web) app structure

---

.github/workflows/design-tokens.yml

Only the changes for the selected ORG are staged/committed. Everything is committed when the default `all` is selected.
1. I made changes in Figma to Troms and AtB
2. I ran the workflow for AtB only. Created this PR: https://github.com/AtB-AS/design-system/pull/224
3. I ran the workflow for all: Created this PR: https://github.com/AtB-AS/design-system/pull/225

feat: Choose org to fetch tokens for

---

packages/theme/README.md
packages/theme/src/generated/themes-fs/atb-theme/dark.css
packages/theme/src/generated/themes-fs/atb-theme/light.css
packages/theme/src/generated/themes-fs/atb-theme/theme.css
packages/theme/src/generated/themes-fs/farte-theme/dark.css
packages/theme/src/generated/themes-fs/farte-theme/light.css
packages/theme/src/generated/themes-fs/farte-theme/theme.css
packages/theme/src/generated/themes-fs/fram-theme/dark.css
packages/theme/src/generated/themes-fs/fram-theme/light.css
packages/theme/src/generated/themes-fs/fram-theme/theme.css
packages/theme/src/generated/themes-fs/innlandet-theme/dark.css
packages/theme/src/generated/themes-fs/innlandet-theme/light.css
packages/theme/src/generated/themes-fs/innlandet-theme/theme.css
packages/theme/src/generated/themes-fs/nfk-theme/dark.css
packages/theme/src/generated/themes-fs/nfk-theme/light.css
packages/theme/src/generated/themes-fs/nfk-theme/theme.css
packages/theme/src/generated/themes-fs/troms-theme/dark.css
packages/theme/src/generated/themes-fs/troms-theme/light.css
packages/theme/src/generated/themes-fs/troms-theme/theme.css
packages/theme/src/generated/themes-fs/vkt-theme/dark.css
packages/theme/src/generated/themes-fs/vkt-theme/light.css
packages/theme/src/generated/themes-fs/vkt-theme/theme.css
packages/theme/tools/fetch-figma-variables.ts

In the generated CSS files, we used the follow syntax
```
@import URL layer(LAYER_NAME) (MEDIA_QUERY)
```
However, NextJS seems to have trouble with this syntax without relying on external plugins such as `postcss-import` (see https://github.com/vercel/next.js/issues/55763 for more info).
Therefore, we are getting rid of the layers, which means that we need a more specific selector to define the current theme. Without layers, :root with a media query would always take precedence over class names (e.g. `.light`). This solution remedies that and has been tested in `webshop2`

feat: Added `data-theme` attribute to manage themes

---

packages/theme/src/theme.ts

We added brand color tokens in Figma, but now they need to be accessible through the Theme type before we can use them

feat: Added brand color tokens to Theme type

---

packages/theme/src/theme.ts

Needed to update the ts types before publishing new design system changes, so this adds `radius.large` and `transport.shuttle`.

fix: add missing radius and shuttle typescript types

---

packages/theme/tools/create-typo.ts
packages/theme/tsconfig.build.json
packages/theme/tsconfig.json

Attempt to fix the issue encountered here:
https://github.com/AtB-AS/design-system/actions/runs/17293053518/job/49084692347
```
/home/runner/work/design-system/design-system/packages/theme/tools/create-typo.ts:13
const base = join(__dirname, '../src/generated');
^
ReferenceError: __dirname is not defined in ES module scope
```

build: add module es2020
