AtB-AS/design-system

- packages/assets/README.md
- packages/assets/package.json
- packages/assets/src/bin.ts
- packages/assets/src/generate.ts
- yarn.lock
Causes minor release bump. Backwards compatible change.
> feat(generate-assets): adds ability to filter by glob

- packages/theme/src/themes/atb-theme/theme.css
- packages/theme/src/themes/atb-theme/theme.module.css
Tilhørende genererte filer til #38
> chore: add generated files

- packages/assets/files/common/colors/icons/actions/ChatUnread.svg
> fix: update ChatUnread.svg color

- packages/theme/src/themes/nfk-theme/theme.css
- packages/theme/src/themes/nfk-theme/theme.module.css
About 1.7 seconds after clicking merge on #43 , I realized it might be a good idea to build the css files as well 😬
> fix: add missing build files

- packages/theme/src/typography.css
- packages/theme/src/typography.module.css
- packages/theme/src/typography/android.ts
- packages/theme/src/typography/ios.ts
Ref: https://github.com/AtB-AS/kundevendt/issues/1666
> update font size of label uppercase to 10 from 8

- packages/theme/src/typography.css
- packages/theme/src/typography.module.css
- packages/theme/src/typography/android.ts
- packages/theme/src/typography/ios.ts
- packages/theme/src/typography/types.ts
Needed in https://github.com/AtB-AS/kundevendt/issues/434
Figma ref: https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App-1.2?node-id=7967%3A70249
Theme ref: https://www.figma.com/file/3rlcixpbhfBglNSctUkMys/Theme-1.0?node-id=26%3A2
> feat: add heading--jumbo

- packages/assets/package.json
- packages/theme/package.json
- yarn.lock
Updates dependencies, removing some audit errors.
> chore: update dependencies

- packages/assets/src/generate.ts
Change order of imports to trigger new release.
> fix: trigger new release

- packages/theme/src/themes/nfk-theme/theme.css
- packages/theme/src/themes/nfk-theme/theme.module.css
- packages/theme/src/themes/nfk-theme/theme.ts
Added a brighter color for interactive 2 hover to fix contrast issues in webshop for NFK.
> fix: interactive-2 hover color change for NFK

- packages/theme/src/themes/nfk-theme/theme.css
- packages/theme/src/themes/nfk-theme/theme.module.css
- packages/theme/src/themes/nfk-theme/theme.ts
* Updated interactive 2 color for NFK according to new color scheme. 
* Changed the color for background_accent_2 so that the "pills" in the webshop have a background color. 
* Add background_accent_1 according to https://www.figma.com/file/0XKBtzHsG9Rep1NcVDeyIu/Nye-farger-varianter?node-id=1%3A3871
> Update NFK colors

- packages/theme/src/themes/nfk-theme/theme.css
- packages/theme/src/themes/nfk-theme/theme.module.css
- packages/theme/src/themes/nfk-theme/theme.ts
Updating NFK dark mode interactive colours 0 and 2, as per by instructions from the NFK designer. (#02414F for both)
> refactor: Update NFK hover colours

- packages/theme/src/theme.ts
- packages/theme/src/themes/atb-theme/theme.css
- packages/theme/src/themes/atb-theme/theme.module.css
- packages/theme/src/themes/atb-theme/theme.ts
- packages/theme/src/themes/fram-theme/theme.css
- packages/theme/src/themes/fram-theme/theme.module.css
- packages/theme/src/themes/fram-theme/theme.ts
- packages/theme/src/themes/nfk-theme/theme.css
- packages/theme/src/themes/nfk-theme/theme.module.css
- packages/theme/src/themes/nfk-theme/theme.ts
Relates: https://github.com/AtB-AS/kundevendt/issues/2837
> feat: Add destructive color

- packages/theme/src/themes/atb-theme/theme.css
- packages/theme/src/themes/atb-theme/theme.module.css
- packages/theme/src/themes/atb-theme/theme.ts
closes https://github.com/AtB-AS/kundevendt/issues/3040
> refactor: change dark secondary text color to gray_100

- packages/theme/src/themes/fram-theme/theme.css
- packages/theme/src/themes/fram-theme/theme.module.css
Built the theme-package and committing as it was forgotten in https://github.com/AtB-AS/design-system/pull/108
> fix: build and commit theme after changes

- packages/theme/src/themes/fram-theme/theme.css
- packages/theme/src/themes/fram-theme/theme.module.css
- packages/theme/src/themes/fram-theme/theme.ts
Closes https://github.com/AtB-AS/kundevendt/issues/3632
Update header and footer colors for FRAM
> refactor: update FRAM header/footer colors

- packages/theme/src/themes/fram-theme/theme.css
- packages/theme/src/themes/fram-theme/theme.module.css
- packages/theme/src/themes/fram-theme/theme.ts
Solves https://github.com/AtB-AS/kundevendt/issues/3664
Added correct text colors and new primary color for FRAM that is compliant with WCAG 1.4.3.
> fix: correct text colors and update primary color for FRAM

- packages/theme/src/themes/fram-theme/theme.css
- packages/theme/src/themes/fram-theme/theme.module.css
- packages/theme/src/themes/fram-theme/theme.ts
Closes https://github.com/AtB-AS/kundevendt/issues/3542
> feat: new color for status info for FRAM

- packages/theme/src/theme.ts
- packages/theme/src/themes/atb-theme/theme.css
- packages/theme/src/themes/atb-theme/theme.module.css
- packages/theme/src/themes/atb-theme/theme.ts
- packages/theme/src/themes/fram-theme/theme.css
- packages/theme/src/themes/fram-theme/theme.module.css
- packages/theme/src/themes/fram-theme/theme.ts
- packages/theme/src/themes/nfk-theme/theme.css
- packages/theme/src/themes/nfk-theme/theme.module.css
- packages/theme/src/themes/nfk-theme/theme.ts
I have made no attempts to check if the colors are working for NFK or Fram. This can be done when these companies consider using these features.
> feat: Add theme support for scooter and bike colors

- packages/theme/src/themes/atb-theme/theme.css
- packages/theme/src/themes/atb-theme/theme.module.css
- packages/theme/src/themes/atb-theme/theme.ts
resolves https://github.com/AtB-AS/kundevendt/issues/5709
Changed primary and secondary colors in themes.dark.transport.transport_other in theme.ts.
> chore: update transport_other dark mode colors

- packages/theme/src/typography.css
- packages/theme/src/typography.module.css
- packages/theme/src/typography/android.ts
- packages/theme/src/typography/ios.ts
- packages/theme/src/typography/types.ts
closes https://github.com/AtB-AS/kundevendt/issues/16521
> feat: add body__tertiary--bold

- packages/theme/src/themes/atb-theme/theme.css
- packages/theme/src/themes/atb-theme/theme.module.css
- packages/theme/src/themes/atb-theme/theme.ts
resolves https://github.com/AtB-AS/kundevendt/issues/15379
> feat: update atb status colors

- packages/theme/src/themes/troms-theme/theme.css
- packages/theme/src/themes/troms-theme/theme.module.css
- packages/theme/src/themes/troms-theme/theme.ts
part of https://github.com/AtB-AS/kundevendt/issues/15379
https://www.figma.com/design/3rlcixpbhfBglNSctUkMys/Text%2C-colors%2C-sizes-and-effects?node-id=5162-6902&t=WR3gMLvREYjOT2b1-0
> feat: update troms status colors

- packages/theme/src/themes/innlandet-theme/theme.css
- packages/theme/src/themes/innlandet-theme/theme.module.css
- packages/theme/src/themes/innlandet-theme/theme.ts
Copied over the changes from https://github.com/AtB-AS/design-system/pull/190 to innlandet theme
> feat: sync innlandet theme with atb updates

- packages/theme/src/themes/atb-theme/theme.css
- packages/theme/src/themes/atb-theme/theme.module.css
- packages/theme/src/themes/atb-theme/theme.ts
closes https://github.com/AtB-AS/kundevendt/issues/18463
> feat: adjust gray atb base colors

- packages/token/README.md
- packages/token/index.js
- packages/token/index.test.js
- packages/token/package.json
- yarn.lock
Added a PostCSS plugin that ensures variables exist
I tested the plugin in Webshop2 during development. Using the token function in a .module.css file there resulted in the correct compiled variable and errors when I referenced a non-existing variable.
For more info, read the README.md
> feat: Added PostCSS plugin for typesafe CSS variables

- packages/assets/package.json
- packages/theme/package.json
This reverts commit dd6507ee8945dec50e8bea79f4ada056f6ccc0bf.
An error occurred during the latest attempt to publish a new version and the packages were not released. Reverting this so that we can do a new release
> Revert "Publish"

- packages/assets/files/common/mono/navigation/ArrowDown.svg
- packages/assets/files/common/mono/navigation/ArrowUp.svg
These are the old icons, but we added them such that I don't have to take replacing all the icons into my (onboarding) scope for mye current task.
> fix: Added up and down arrows

- packages/assets/package.json
This reverts commit a4b5f0f1bf81c3991134c028d6c86973b3a47538.
Failed release wasn't published to npm, so trying to reset things before we release again.
> revert: revert "Publish"

- .github/workflows/design-tokens.yml
- .github/workflows/release.yml
- .github/workflows/sematic-pr.yml
- .release-please-manifest.json
- README.md
- lerna.json
- package.json
- packages/assets/package.json
- release-please-config.json
- yarn.lock
This will create release-please PRs for each package that has changes with semantic commit messages. Also added an action that verifies semantic PR titles to hopefully prevent issues occurring with releases. 
See working builds in my fork: https://github.com/rosvik/design-system
closes https://github.com/AtB-AS/kundevendt/issues/21092
> ci: add release please workflow

- package.json
- yarn.lock
Follow-up to https://github.com/AtB-AS/design-system/pull/334
Attempt to fix https://github.com/AtB-AS/design-system/actions/runs/17547649537/job/49832729358
> chore: Use same ts version in all package.json
